#DB
DB_NAME = "anomaly_db"

#ANOMALIES TABLE 
ANOMALY_TABLE_NAME="anomalies"
ANOMALY_ID="anomalyId"
ANOMALY_USER_ID="userId"
ANOMALY_CATEGORY="category"
ANOMALY_QUANTITY="quantity"
ANOMALY_START_DATE="startDate"
ANOMALY_END_DATE_="endDate"

#USER STATISTICS TABLE
USER_STATISTIC_TABLE_NAME="user_statistics"
USER_STATISTICS_USER_ID="userId"
USER_STATISTICS_AVG_NUM_OF_WITHDRAWS="avgNumOfWithdraws"
USER_STATISTICS_AVG_NUM_OF_DEPOSITS="avgNumOfDeposits"
USER_STATISTICS_AVG_AMOUNT_WITHDRAW="avgAmountWithdraw"
USER_STATISTICS_AVG_AMOUNT_DEPOSIT="avgAmountDeposit"
USER_STATISTICS_NUM_OF_UPDATES="numOfUpdates"

#CONNECTION INFORMATION
CONNECTION_HOST = "localhost"
CONNECTION_USER = "root"
CONNECTION_PASSWORD = ""
CONNECTION_CHARSET = "utf8"



